services:
  app:
    image: daryazakhar89/app
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - myNetwork
    depends_on:
      - database
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - ./src:/src
    restart: always
    # command: ['npm', 'run', 'start:dev']
  database:
    image: daryazakhar89/postgres-image
    container_name: db
    build: ./database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database:/var/lib/postgresql/data 777
    restart: always
    networks:
      - myNetwork
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  myNetwork:
    driver: bridge
