services:
  app:
    image: daryazakhar89/app
    container_name: app
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/src
    networks:
      - myNetwork
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - database
    restart: always

  database:
    image: daryazakhar89/postgres-image
    container_name: db
    build: ./database
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
    volumes:
      - ./database:/var/lib/postgresql/data 777
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
